/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/foukas/hobbit/src/decision_service/srv/GetProfileAttributesWithPrefix.srv
 *
 */


#ifndef DECISION_SERVICE_MESSAGE_GETPROFILEATTRIBUTESWITHPREFIX_H
#define DECISION_SERVICE_MESSAGE_GETPROFILEATTRIBUTESWITHPREFIX_H

#include <ros/service_traits.h>


#include <decision_service/GetProfileAttributesWithPrefixRequest.h>
#include <decision_service/GetProfileAttributesWithPrefixResponse.h>


namespace decision_service
{

struct GetProfileAttributesWithPrefix
{

typedef GetProfileAttributesWithPrefixRequest Request;
typedef GetProfileAttributesWithPrefixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetProfileAttributesWithPrefix
} // namespace decision_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::decision_service::GetProfileAttributesWithPrefix > {
  static const char* value()
  {
    return "2071c5a44bea145ab0030a2f455a3564";
  }

  static const char* value(const ::decision_service::GetProfileAttributesWithPrefix&) { return value(); }
};

template<>
struct DataType< ::decision_service::GetProfileAttributesWithPrefix > {
  static const char* value()
  {
    return "decision_service/GetProfileAttributesWithPrefix";
  }

  static const char* value(const ::decision_service::GetProfileAttributesWithPrefix&) { return value(); }
};


// service_traits::MD5Sum< ::decision_service::GetProfileAttributesWithPrefixRequest> should match 
// service_traits::MD5Sum< ::decision_service::GetProfileAttributesWithPrefix > 
template<>
struct MD5Sum< ::decision_service::GetProfileAttributesWithPrefixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::decision_service::GetProfileAttributesWithPrefix >::value();
  }
  static const char* value(const ::decision_service::GetProfileAttributesWithPrefixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_service::GetProfileAttributesWithPrefixRequest> should match 
// service_traits::DataType< ::decision_service::GetProfileAttributesWithPrefix > 
template<>
struct DataType< ::decision_service::GetProfileAttributesWithPrefixRequest>
{
  static const char* value()
  {
    return DataType< ::decision_service::GetProfileAttributesWithPrefix >::value();
  }
  static const char* value(const ::decision_service::GetProfileAttributesWithPrefixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::decision_service::GetProfileAttributesWithPrefixResponse> should match 
// service_traits::MD5Sum< ::decision_service::GetProfileAttributesWithPrefix > 
template<>
struct MD5Sum< ::decision_service::GetProfileAttributesWithPrefixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::decision_service::GetProfileAttributesWithPrefix >::value();
  }
  static const char* value(const ::decision_service::GetProfileAttributesWithPrefixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_service::GetProfileAttributesWithPrefixResponse> should match 
// service_traits::DataType< ::decision_service::GetProfileAttributesWithPrefix > 
template<>
struct DataType< ::decision_service::GetProfileAttributesWithPrefixResponse>
{
  static const char* value()
  {
    return DataType< ::decision_service::GetProfileAttributesWithPrefix >::value();
  }
  static const char* value(const ::decision_service::GetProfileAttributesWithPrefixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DECISION_SERVICE_MESSAGE_GETPROFILEATTRIBUTESWITHPREFIX_H
