/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/foukas/hobbit/src/decision_service/srv/SetGlobalBoolConditional.srv
 *
 */


#ifndef DECISION_SERVICE_MESSAGE_SETGLOBALBOOLCONDITIONAL_H
#define DECISION_SERVICE_MESSAGE_SETGLOBALBOOLCONDITIONAL_H

#include <ros/service_traits.h>


#include <decision_service/SetGlobalBoolConditionalRequest.h>
#include <decision_service/SetGlobalBoolConditionalResponse.h>


namespace decision_service
{

struct SetGlobalBoolConditional
{

typedef SetGlobalBoolConditionalRequest Request;
typedef SetGlobalBoolConditionalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalBoolConditional
} // namespace decision_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::decision_service::SetGlobalBoolConditional > {
  static const char* value()
  {
    return "44b8d83711036e049f679c62a51c479e";
  }

  static const char* value(const ::decision_service::SetGlobalBoolConditional&) { return value(); }
};

template<>
struct DataType< ::decision_service::SetGlobalBoolConditional > {
  static const char* value()
  {
    return "decision_service/SetGlobalBoolConditional";
  }

  static const char* value(const ::decision_service::SetGlobalBoolConditional&) { return value(); }
};


// service_traits::MD5Sum< ::decision_service::SetGlobalBoolConditionalRequest> should match 
// service_traits::MD5Sum< ::decision_service::SetGlobalBoolConditional > 
template<>
struct MD5Sum< ::decision_service::SetGlobalBoolConditionalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::decision_service::SetGlobalBoolConditional >::value();
  }
  static const char* value(const ::decision_service::SetGlobalBoolConditionalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_service::SetGlobalBoolConditionalRequest> should match 
// service_traits::DataType< ::decision_service::SetGlobalBoolConditional > 
template<>
struct DataType< ::decision_service::SetGlobalBoolConditionalRequest>
{
  static const char* value()
  {
    return DataType< ::decision_service::SetGlobalBoolConditional >::value();
  }
  static const char* value(const ::decision_service::SetGlobalBoolConditionalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::decision_service::SetGlobalBoolConditionalResponse> should match 
// service_traits::MD5Sum< ::decision_service::SetGlobalBoolConditional > 
template<>
struct MD5Sum< ::decision_service::SetGlobalBoolConditionalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::decision_service::SetGlobalBoolConditional >::value();
  }
  static const char* value(const ::decision_service::SetGlobalBoolConditionalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_service::SetGlobalBoolConditionalResponse> should match 
// service_traits::DataType< ::decision_service::SetGlobalBoolConditional > 
template<>
struct DataType< ::decision_service::SetGlobalBoolConditionalResponse>
{
  static const char* value()
  {
    return DataType< ::decision_service::SetGlobalBoolConditional >::value();
  }
  static const char* value(const ::decision_service::SetGlobalBoolConditionalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DECISION_SERVICE_MESSAGE_SETGLOBALBOOLCONDITIONAL_H
