ENV/Sensor/CALL1/BusID: "1"
ENV/Sensor/CALL1/NodeID: "298a1e"
ENV/Sensor/CALL1/Place: "CALL1"
ENV/Sensor/CALL1/Type: "CALL|ACTIVITY"
ENV/Sensor/CALL2/BusID: "1"
ENV/Sensor/CALL2/NodeID: "298a29"
ENV/Sensor/CALL2/Place: "CALL2"
ENV/Sensor/CALL2/Type: "CALL|ACTIVITY"
ENV/Sensor/CALL3/BusID: "1"
ENV/Sensor/CALL3/NodeID: "298aa4"
ENV/Sensor/CALL3/Place: "CALL3"
ENV/Sensor/CALL3/Type: "CALL|ACTIVITY"
ENV/Sensor/CALL4/BusID: "1"
ENV/Sensor/CALL4/NodeID: "298a23"
ENV/Sensor/CALL4/Place: "CALL4"
ENV/Sensor/CALL4/Type: "CALL|ACTIVITY"
ENV/Sensor/CALLb/BusID: "1"
ENV/Sensor/CALLb/NodeID: "298a12"
ENV/Sensor/CALLb/Place: "CALLb"
ENV/Sensor/CALLb/Type: "CALL|ACTIVITY|BATHROOM"
ENV/Sensor/PIR1/BusID: "1"
ENV/Sensor/PIR1/NodeID: "89be55"
ENV/Sensor/PIR1/Place: "PIR1"
ENV/Sensor/PIR1/Type: "ACTIVITY"
ENV/Sensor/FLOORLAMP1/BusID: "1"
ENV/Sensor/FLOORLAMP1/NodeID: "0"
ENV/Sensor/FLOORLAMP1/Place: "FLOORLAMP1"
ENV/Sensor/FLOORLAMP1/Type: "ACTUATOR"
ENV/SensorList: "CALL1+++CALL2+++CALL3+++CALL4+++CALLb+++PIR1+++FLOORLAMP1"
