#!/usr/bin/env bash

# requires xdotool, install via ubuntu package manager

xdotool sleep 5
gnome-terminal -t "console"

xdotool key ctrl+shift+t
xdotool sleep 1
xdotool key alt+t
xdotool sleep 1
xdotool key s
xdotool sleep 1
xdotool type "CAMERA"
xdotool key Return
xdotool sleep 1
xdotool type "roslaunch HobbitLaunch top_camera.launch depth_registration:=true"
xdotool sleep 1
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool sleep 1
xdotool key alt+t
xdotool sleep 1
xdotool key s
xdotool sleep 1
xdotool type "Face"
xdotool sleep 1
xdotool key Return
xdotool sleep 1
#xdotool type "roslaunch user_vision startup.launch "
xdotool sleep 1
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool sleep 1
xdotool key alt+t
xdotool sleep 1
xdotool key s
xdotool sleep 1
xdotool type "ptpd"
xdotool key Return
xdotool sleep 1
xdotool type "sudo ptpd -g –b eth0"
xdotool sleep 1
xdotool key Return
xdotool sleep 1
xdotool type "robot"
xdotool key Return
xdotool sleep 1


xdotool key ctrl+shift+t
xdotool key alt+t
xdotool key s
xdotool type "TOD feature"
xdotool key Return
xdotool sleep 1
xdotool type "rosrun TableObjectDetector shapefeature"
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool key alt+t
xdotool key s
xdotool type "TOD feature"
xdotool key Return
xdotool sleep 1
xdotool type "rosrun TableObjectDetector thor"
xdotool key Return
xdotool sleep 1



