#!/bin/bash
# This has to be executed on the xpc
# Place it under /etc/network/if-up.d/

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -A FORWARD --in-interface eth0 -j ACCEPT
iptables --table nat -A POSTROUTING --out-interface wlan0 -j MASQUERADE
