#!/usr/bin/env bash

# requires xdotool, install via ubuntu package manager

gnome-terminal -t "console"
xdotool key alt+t
xdotool key s
xdotool type "roscore"
xdotool key Return
xdotool sleep 1
xdotool type "roscore"
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool key alt+t
xdotool key s
xdotool type "Base Camera"
xdotool key Return
xdotool sleep 1
xdotool type "roslaunch HobbitLaunch top_camera.launch "
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool key alt+t
xdotool key s
xdotool type "Top Camera"
xdotool key Return
xdotool sleep 1
xdotool type "roslaunch HobbitLaunch base_camera.launch "
xdotool key Return
xdotool sleep 1

xdotool key ctrl+shift+t
xdotool key alt+t
xdotool key s
xdotool type "Background Tools"
xdotool key Return
xdotool sleep 1
xdotool type "roslaunch HobbitLaunch startup_profiles.launch "
xdotool key Return
xdotool sleep 1


#xdotool key ctrl+shift+t
#xdotool key alt+t
#xdotool key s
#xdotool type "AR Markers"
##xdotool key Return
#xdotool sleep 0.1
#xdotool type "roslaunch ar_marker lwr.launch"
#xdotool key Return

#xdotool key ctrl+shift+t
#xdotool key alt+t
#xdotool key s
#xdotool type "OttoBockHand"
#xdotool key Return
#xdotool sleep 0.1
#xdotool type "sudo rfcomm connect hci0 10:00:E8:AD:DF:2D"
#xdotool key Return
#xdotool sleep 2
#xdotool key ctrl+c
##xdotool type "roslaunch michelangelo_hand_rospkg michelangelo_hand_node.launch"
#xdotool key Return


#xdotool key ctrl+shift+t
#xdotool key alt+t
#xdotool key s
#xdotool type "Demo Master"
#xdotool key Return
#xdotool sleep 0.1
#xdotool type "cd /home/walter/ros/graspdemo_categorization/demo_master/"
#xdotool key Return
#xdotool type "./bin/master -models_dir /home/walter/3DNET/AA/ -training_dir /home/walter/3DNET/AAT/ -z_dist 1 "
#xdotool key Return


#xdotool key ctrl+shift+t
#xdotool key alt+t
#xdotool key s
#xdotool type "LWRComm"
#xdotool key Return
#xdotool sleep 0.1
#xdotool type "sudo -s"
#xdotool key Return
#xdotool type "rosrun lwrcontrol comm"
#xdotool key Return

#xdotool key ctrl+shift+t
#xdotool key alt+t
#xdotool key s
#xdotool type "OpenRave"
#xdotool key Return
#xdotool sleep 0.1
#xdotool type "roslaunch openrave_simulation tt_simulation_planning.launch"
#xdotool key Return








